### ISSUE TITLE
No active profile set

### ISSUE THREAD

**Issue by gadieichhorn** [IG-Group/ig-webapi-javascript-sample#1]
Hi, thanks for the example project.

I try to use it after setting my API key and different user / pass on the Demo account.

> No active profile set, falling back to default profiles: default

and then:

> 400 bad request

Any idea how to set the profile?
Maybe there is a more recent example project?

**Comment by gadieichhorn** [comment]
resolved by changing my username

**Comment by ireay** [comment]
Glad you got this sorted. Please use the community board on https://labs.ig.com/

Ian
